/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
         classpath(kotlin("gradle-plugin", version = "1.3.31"))
    }
}

plugins {
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
    application
}

repositories {
    jcenter()
}

dependencies {
    implementation(fileTree("lib"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    mainClassName = "boundaryvalueproblem.AppKt"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "boundaryvalueproblem.AppKt"
    }
    
    from(configurations.compile.get().map { if (it.isDirectory()) it else zipTree(it) }) 
}